/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import utilities.mycompany.DBConext.HibernatUtil;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import domainModels.DongSP;
import domainModels.MauSac;
import domainModels.NSX;
import domainModels.SanPham;
import services.DongSpService;
import services.MauSacService;
import services.NSXService;
import services.SPService;
import viewModels.DongSPVmodel;
import viewModels.MauSacViewModel;
import viewModels.NSXViewModel;
import viewModels.SanPhamVModel;
import services.Impl.IManageDongSPService;
import services.Impl.IManageMauSacService;
import services.Impl.IManageNSXService;
import services.Impl.IManageSanPhamService;

/**
 *
 * @author Admin
 */
public class viewSanPham extends javax.swing.JFrame {

    /**
     * Creates new form viewSanPham
     */
    private final IManageSanPhamService service = new SPService();
    private final IManageNSXService serviceNSX = new NSXService();
    private final IManageDongSPService serviceDongSP = new DongSpService();
    private final IManageMauSacService serviceMauSac = new MauSacService();
    DefaultTableModel model = new DefaultTableModel();

    public viewSanPham(String Id, String Ma, String Ten) {
        initComponents();
        txtIdNhanVien.setText(Id);
        txtMaNV.setText(Ma);
        txtTenNV.setText(Ten);
        //
        loadSP();
        loadNSX();
        loadMauSax();
        loadDongSP();

    }

    public void loadSP() {
        List<SanPhamVModel> lists = service.getSp();

        model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);

        for (SanPhamVModel s : lists) {
            model.addRow(new Object[]{
                s.getId(), s.getMa(), s.getTen()
            });
        }
    }

    public void loadNSX() {
        List<NSXViewModel> lists = serviceNSX.getNSX();

        model = (DefaultTableModel) tblNSX.getModel();
        model.setRowCount(0);

        for (NSXViewModel s : lists) {
            model.addRow(new Object[]{
                s.getId(), s.getMa(), s.getTen()
            });
        }
    }

    public void loadDongSP() {
        List<DongSPVmodel> lists = serviceDongSP.getlist();

        model = (DefaultTableModel) tblDongSP.getModel();
        model.setRowCount(0);

        for (DongSPVmodel s : lists) {
            model.addRow(new Object[]{
                s.getId(), s.getMa(), s.getTen()
            });
        }
    }

    public void loadMauSax() {
        List<MauSacViewModel> lists = serviceMauSac.getlist();

        model = (DefaultTableModel) tblMauSac.getModel();
        model.setRowCount(0);

        for (MauSacViewModel s : lists) {
            model.addRow(new Object[]{
                s.getId(), s.getMa(), s.getTen()
            });
        }
    }

    public boolean checkMaSp(String masp) {
        try {
            List<SanPhamVModel> lists = service.getSp();
            for (SanPhamVModel s : lists) {
                if (s.getMa().equalsIgnoreCase(masp)) {
                    return false;
                }
            }
        } catch (Exception e) {
        }
        return true;
    }

    public boolean checkMaNSX(String mansx) {
        try {
            List<NSXViewModel> lists = serviceNSX.getNSX();
            for (NSXViewModel s : lists) {
                if (s.getMa().equalsIgnoreCase(mansx)) {
                    return false;
                }
            }
        } catch (Exception e) {
        }
        return true;
    }

    public boolean checkMaMauSac(String ma) {
        try {
            List<MauSacViewModel> lists = serviceMauSac.getlist();
            for (MauSacViewModel s : lists) {
                if (s.getMa().equalsIgnoreCase(ma)) {
                    return false;
                }
            }
        } catch (Exception e) {
        }
        return true;
    }

    public boolean checkMaDongSP(String ma) {
        try {
            List<DongSPVmodel> lists = serviceDongSP.getlist();
            for (DongSPVmodel s : lists) {
                if (s.getMa().equalsIgnoreCase(ma)) {
                    return false;
                }
            }
        } catch (Exception e) {
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        txtIdNhanVien = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbIDSP = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        txtMaSP = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        addSp = new javax.swing.JButton();
        UpdateSp = new javax.swing.JButton();
        DeleteSp4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNSX = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbIIdNSX = new javax.swing.JLabel();
        txtTenNSX = new javax.swing.JTextField();
        txtMaNSX = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        addSp8 = new javax.swing.JButton();
        UpdateSp2 = new javax.swing.JButton();
        DeleteSp2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDongSP = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbIIDDongSP = new javax.swing.JLabel();
        txtTenDongSP = new javax.swing.JTextField();
        txtMaDongSP = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        addSp9 = new javax.swing.JButton();
        UpdateSp8 = new javax.swing.JButton();
        DeleteSp8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblMauSac = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbIIdMauSac = new javax.swing.JLabel();
        txtTenMauSac = new javax.swing.JTextField();
        txtMaMauSac = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        addSp10 = new javax.swing.JButton();
        UpdateSp9 = new javax.swing.JButton();
        DeleteSp9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jPanel14.setBackground(new java.awt.Color(153, 153, 255));

        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.setForeground(new java.awt.Color(153, 153, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/coffeShop.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel15.setBackground(new java.awt.Color(153, 102, 255));

        txtIdNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtIdNhanVien.setText("Id");

        txtMaNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMaNV.setText("Ma NV");

        txtTenNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTenNV.setText("Ten NV");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtIdNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addGap(191, 191, 191)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(192, Short.MAX_VALUE)))
        );

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 255));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ma", "Ten"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Id");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Ma");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Ten");

        lbIDSP.setBackground(new java.awt.Color(0, 0, 0));
        lbIDSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbIDSP.setText("Id");

        txtTenSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtMaSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbIDSP, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbIDSP))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel13.setBackground(new java.awt.Color(153, 153, 255));

        addSp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/themmoiicon.png"))); // NOI18N
        addSp.setText("Add");
        addSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSpActionPerformed(evt);
            }
        });

        UpdateSp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/updateicon.png"))); // NOI18N
        UpdateSp.setText("Update");
        UpdateSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateSpActionPerformed(evt);
            }
        });

        DeleteSp4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/deleteicon.png"))); // NOI18N
        DeleteSp4.setText("Delete");
        DeleteSp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSp4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addSp, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateSp, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteSp4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addSp, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateSp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteSp4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Sản Phẩm", jPanel2);

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        tblNSX.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ma", "Ten"
            }
        ));
        tblNSX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNSXMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblNSX);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Id");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Ma");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Ten");

        lbIIdNSX.setBackground(new java.awt.Color(0, 0, 0));
        lbIIdNSX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbIIdNSX.setText("Id");

        txtTenNSX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtMaNSX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenNSX, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaNSX, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbIIdNSX, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbIIdNSX))
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMaNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTenNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel18.setBackground(new java.awt.Color(153, 153, 255));

        addSp8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/themmoiicon.png"))); // NOI18N
        addSp8.setText("Add");
        addSp8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSp8ActionPerformed(evt);
            }
        });

        UpdateSp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/updateicon.png"))); // NOI18N
        UpdateSp2.setText("Update");
        UpdateSp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateSp2ActionPerformed(evt);
            }
        });

        DeleteSp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/deleteicon.png"))); // NOI18N
        DeleteSp2.setText("Delete");
        DeleteSp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSp2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addSp8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateSp2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteSp2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addSp8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateSp2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteSp2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Nhà Sản Xuất", jPanel3);

        jPanel9.setBackground(new java.awt.Color(153, 153, 255));
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));

        tblDongSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ma", "Ten"
            }
        ));
        tblDongSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDongSPMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDongSP);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Id");

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Ma");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Ten");

        lbIIDDongSP.setBackground(new java.awt.Color(0, 0, 0));
        lbIIDDongSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbIIDDongSP.setText("Id");

        txtTenDongSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtMaDongSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenDongSP, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaDongSP, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbIIDDongSP, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lbIIDDongSP))
                .addGap(27, 27, 27)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtMaDongSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtTenDongSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel19.setBackground(new java.awt.Color(153, 153, 255));

        addSp9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/themmoiicon.png"))); // NOI18N
        addSp9.setText("Add");
        addSp9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSp9ActionPerformed(evt);
            }
        });

        UpdateSp8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/updateicon.png"))); // NOI18N
        UpdateSp8.setText("Update");
        UpdateSp8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateSp8ActionPerformed(evt);
            }
        });

        DeleteSp8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/deleteicon.png"))); // NOI18N
        DeleteSp8.setText("Delete");
        DeleteSp8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSp8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addSp9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateSp8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteSp8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addSp9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateSp8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteSp8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Dòng Sản Phẩm", jPanel4);

        jPanel11.setBackground(new java.awt.Color(153, 153, 255));
        jPanel11.setForeground(new java.awt.Color(255, 255, 255));

        tblMauSac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ma", "Ten"
            }
        ));
        tblMauSac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMauSacMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblMauSac);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Id");

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Ma");

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Ten");

        lbIIdMauSac.setBackground(new java.awt.Color(0, 0, 0));
        lbIIdMauSac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbIIdMauSac.setText("Id");

        txtTenMauSac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtMaMauSac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbIIdMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lbIIdMauSac))
                .addGap(27, 27, 27)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtMaMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtTenMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel20.setBackground(new java.awt.Color(153, 153, 255));

        addSp10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/themmoiicon.png"))); // NOI18N
        addSp10.setText("Add");
        addSp10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSp10ActionPerformed(evt);
            }
        });

        UpdateSp9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/updateicon.png"))); // NOI18N
        UpdateSp9.setText("Update");
        UpdateSp9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateSp9ActionPerformed(evt);
            }
        });

        DeleteSp9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/deleteicon.png"))); // NOI18N
        DeleteSp9.setText("Delete");
        DeleteSp9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSp9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addSp10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateSp9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteSp9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addSp10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateSp9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteSp9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Màu Sắc", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MenuView v = new MenuView(txtIdNhanVien.getText(), txtMaNV.getText(), txtTenNV.getText());
        v.setLocationRelativeTo(null);
        v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void DeleteSp9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSp9ActionPerformed
        if (lbIIdMauSac.getText().equals("Id")) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Chưa Chọn Sản Phẩm Update", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }

        boolean b = serviceMauSac.delete(lbIIdMauSac.getText());
        if (b == true) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/clear.png"));
            JOptionPane.showMessageDialog(this, "delete Sản Phẩm Thành Công", "Giỏ Hàng", JOptionPane.INFORMATION_MESSAGE, icon);
            loadMauSax();
        } else {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/deleteicon.png"));
            JOptionPane.showMessageDialog(this, "Sản Phẩm Đã Được Bán Không Thể Delete", "Giỏ Hàng !", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_DeleteSp9ActionPerformed

    private void UpdateSp9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateSp9ActionPerformed
        if (lbIIdMauSac.getText().equals("Id")) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Chưa Chọn Sản Phẩm Update", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }

        if (txtTenMauSac.getText().equals("")) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Chưa Nhập Tên", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }

        boolean b = serviceMauSac.update(txtTenMauSac.getText(), lbIIdMauSac.getText());
        if (b == true) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/clear.png"));
            JOptionPane.showMessageDialog(this, "Update Sản Phẩm Thành Công", "Giỏ Hàng", JOptionPane.INFORMATION_MESSAGE, icon);
            loadMauSax();
        } else {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/deleteicon.png"));
            JOptionPane.showMessageDialog(this, "Update Sản Phẩm Thất Bại", "Giỏ Hàng !", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_UpdateSp9ActionPerformed

    private void addSp10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSp10ActionPerformed
        if (txtMaMauSac.getText().equals("")) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Chưa Nhập Mã", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }
        if (txtTenMauSac.getText().equals("")) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Chưa Nhập Tên", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }
        if (checkMaMauSac(txtMaMauSac.getText()) == false) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Mã Sản Phẩm Đã Tồn Tại", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }
        MauSac s = new MauSac();
        s.setMa(txtMaMauSac.getText());
        s.setTen(txtTenMauSac.getText());
        boolean b = serviceMauSac.add(s);
        if (b == true) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/clear.png"));
            JOptionPane.showMessageDialog(this, "Add Sản Phẩm Thành Công", "Giỏ Hàng", JOptionPane.INFORMATION_MESSAGE, icon);
            loadMauSax();
        } else {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/deleteicon.png"));
            JOptionPane.showMessageDialog(this, "Add Sản Phẩm Thất Bại", "Giỏ Hàng !", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_addSp10ActionPerformed

    private void tblMauSacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMauSacMouseClicked
        List<MauSacViewModel> lists = serviceMauSac.getlist();
        int index = tblMauSac.getSelectedRow();
        MauSacViewModel sp = lists.get(index);
        lbIIdMauSac.setText(sp.getId());
        txtMaMauSac.setText(sp.getMa());
        txtTenMauSac.setText(sp.getTen());
    }//GEN-LAST:event_tblMauSacMouseClicked

    private void DeleteSp8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSp8ActionPerformed
        if (lbIIDDongSP.getText().equals("Id")) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Chưa Chọn Sản Phẩm Update", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }

        boolean b = serviceDongSP.delete(lbIIDDongSP.getText());
        if (b == true) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/clear.png"));
            JOptionPane.showMessageDialog(this, "delete Sản Phẩm Thành Công", "Giỏ Hàng", JOptionPane.INFORMATION_MESSAGE, icon);
            loadDongSP();
        } else {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/deleteicon.png"));
            JOptionPane.showMessageDialog(this, "Sản Phẩm Đã Được Bán Không Thể Delete", "Giỏ Hàng !", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_DeleteSp8ActionPerformed

    private void UpdateSp8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateSp8ActionPerformed
        if (lbIIDDongSP.getText().equals("Id")) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Chưa Chọn Sản Phẩm Update", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }

        if (txtTenDongSP.getText().equals("")) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Chưa Nhập Tên", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }

        boolean b = serviceDongSP.update(txtTenDongSP.getText(), lbIIDDongSP.getText());
        if (b == true) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/clear.png"));
            JOptionPane.showMessageDialog(this, "Update Sản Phẩm Thành Công", "Giỏ Hàng", JOptionPane.INFORMATION_MESSAGE, icon);
            loadDongSP();
        } else {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/deleteicon.png"));
            JOptionPane.showMessageDialog(this, "Update Sản Phẩm Thất Bại", "Giỏ Hàng !", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_UpdateSp8ActionPerformed

    private void addSp9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSp9ActionPerformed
        if (txtMaDongSP.getText().equals("")) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Chưa Nhập Mã", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }
        if (txtTenDongSP.getText().equals("")) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Chưa Nhập Tên", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }
        if (checkMaDongSP(txtMaDongSP.getText()) == false) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Mã Sản Phẩm Đã Tồn Tại", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }
        DongSP s = new DongSP();
        s.setMa(txtMaDongSP.getText());
        s.setTen(txtTenDongSP.getText());
        boolean b = serviceDongSP.add(s);
        if (b == true) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/clear.png"));
            JOptionPane.showMessageDialog(this, "Add Sản Phẩm Thành Công", "Giỏ Hàng", JOptionPane.INFORMATION_MESSAGE, icon);
            loadDongSP();
        } else {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/deleteicon.png"));
            JOptionPane.showMessageDialog(this, "Add Sản Phẩm Thất Bại", "Giỏ Hàng !", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_addSp9ActionPerformed

    private void tblDongSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDongSPMouseClicked
        List<DongSPVmodel> lists = serviceDongSP.getlist();
        int index = tblDongSP.getSelectedRow();
        DongSPVmodel sp = lists.get(index);
        lbIIDDongSP.setText(sp.getId());
        txtMaDongSP.setText(sp.getMa());
        txtTenDongSP.setText(sp.getTen());
    }//GEN-LAST:event_tblDongSPMouseClicked

    private void DeleteSp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSp2ActionPerformed
        if (lbIIdNSX.getText().equals("Id")) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Chưa Chọn Sản Phẩm Update", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }

        boolean b = serviceNSX.delete(lbIIdNSX.getText());
        if (b == true) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/clear.png"));
            JOptionPane.showMessageDialog(this, "delete Sản Phẩm Thành Công", "Giỏ Hàng", JOptionPane.INFORMATION_MESSAGE, icon);
            loadNSX();
        } else {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/deleteicon.png"));
            JOptionPane.showMessageDialog(this, "Sản Phẩm Đã Được Bán Không Thể Delete", "Giỏ Hàng !", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_DeleteSp2ActionPerformed

    private void UpdateSp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateSp2ActionPerformed
        if (lbIIdNSX.getText().equals("Id")) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Chưa Chọn Sản Phẩm Update", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }

        if (txtTenNSX.getText().equals("")) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Chưa Nhập Tên", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }

        boolean b = serviceNSX.update(txtTenNSX.getText(), lbIIdNSX.getText());
        if (b == true) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/clear.png"));
            JOptionPane.showMessageDialog(this, "Update Sản Phẩm Thành Công", "Giỏ Hàng", JOptionPane.INFORMATION_MESSAGE, icon);
            loadNSX();
        } else {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/deleteicon.png"));
            JOptionPane.showMessageDialog(this, "Update Sản Phẩm Thất Bại", "Giỏ Hàng !", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_UpdateSp2ActionPerformed

    private void addSp8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSp8ActionPerformed
        if (txtMaNSX.getText().equals("")) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Chưa Nhập Mã", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }
        if (txtTenNSX.getText().equals("")) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Chưa Nhập Tên", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }
        if (checkMaNSX(txtMaNSX.getText()) == false) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Mã Sản Phẩm Đã Tồn Tại", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }
        NSX s = new NSX();
        s.setMa(txtMaNSX.getText());
        s.setTen(txtTenNSX.getText());
        boolean b = serviceNSX.add(s);
        if (b == true) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/clear.png"));
            JOptionPane.showMessageDialog(this, "Add Sản Phẩm Thành Công", "Giỏ Hàng", JOptionPane.INFORMATION_MESSAGE, icon);
            loadNSX();
        } else {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/deleteicon.png"));
            JOptionPane.showMessageDialog(this, "Add Sản Phẩm Thất Bại", "Giỏ Hàng !", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_addSp8ActionPerformed

    private void tblNSXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNSXMouseClicked
        List<NSXViewModel> lists = serviceNSX.getNSX();
        int index = tblNSX.getSelectedRow();
        NSXViewModel sp = lists.get(index);
        lbIIdNSX.setText(sp.getId());
        txtMaNSX.setText(sp.getMa());
        txtTenNSX.setText(sp.getTen());
    }//GEN-LAST:event_tblNSXMouseClicked

    private void DeleteSp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSp4ActionPerformed
        if (lbIDSP.getText().equals("Id")) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Chưa Chọn Sản Phẩm Update", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }

        boolean b = service.delete(lbIDSP.getText());
        if (b == true) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/clear.png"));
            JOptionPane.showMessageDialog(this, "delete Sản Phẩm Thành Công", "Giỏ Hàng", JOptionPane.INFORMATION_MESSAGE, icon);
            loadSP();
        } else {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/deleteicon.png"));
            JOptionPane.showMessageDialog(this, "Sản Phẩm Đã Được Bán Không Thể Delete", "Giỏ Hàng !", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_DeleteSp4ActionPerformed

    private void UpdateSpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateSpActionPerformed
        if (lbIDSP.getText().equals("Id")) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Chưa Chọn Sản Phẩm Update", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }

        if (txtTenSP.getText().equals("")) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Chưa Nhập Tên", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }

        boolean b = service.update(txtTenSP.getText(), lbIDSP.getText());
        if (b == true) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/clear.png"));
            JOptionPane.showMessageDialog(this, "Update Sản Phẩm Thành Công", "Giỏ Hàng", JOptionPane.INFORMATION_MESSAGE, icon);
            loadSP();
        } else {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/deleteicon.png"));
            JOptionPane.showMessageDialog(this, "Update Sản Phẩm Thất Bại", "Giỏ Hàng !", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_UpdateSpActionPerformed

    private void addSpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSpActionPerformed
        if (txtMaSP.getText().equals("")) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Chưa Nhập Mã", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }
        if (txtTenSP.getText().equals("")) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Chưa Nhập Tên", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }
        if (checkMaSp(txtMaSP.getText()) == false) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/TraTien.png"));
            JOptionPane.showMessageDialog(this, "Mã Sản Phẩm Đã Tồn Tại", "Horrry !", JOptionPane.INFORMATION_MESSAGE, icon);
            return;
        }
        SanPham s = new SanPham();
        s.setMa(txtMaSP.getText());
        s.setTen(txtTenSP.getText());
        boolean b = service.add(s);
        if (b == true) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/clear.png"));
            JOptionPane.showMessageDialog(this, "Add Sản Phẩm Thành Công", "Giỏ Hàng", JOptionPane.INFORMATION_MESSAGE, icon);
            loadSP();
        } else {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/deleteicon.png"));
            JOptionPane.showMessageDialog(this, "Add Sản Phẩm Thất Bại", "Giỏ Hàng !", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_addSpActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        List<SanPhamVModel> lists = service.getSp();
        int index = tblSanPham.getSelectedRow();
        SanPhamVModel sp = lists.get(index);
        lbIDSP.setText(sp.getId());
        txtMaSP.setText(sp.getMa());
        txtTenSP.setText(sp.getTen());
    }//GEN-LAST:event_tblSanPhamMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteSp2;
    private javax.swing.JButton DeleteSp4;
    private javax.swing.JButton DeleteSp8;
    private javax.swing.JButton DeleteSp9;
    private javax.swing.JButton UpdateSp;
    private javax.swing.JButton UpdateSp2;
    private javax.swing.JButton UpdateSp8;
    private javax.swing.JButton UpdateSp9;
    private javax.swing.JButton addSp;
    private javax.swing.JButton addSp10;
    private javax.swing.JButton addSp8;
    private javax.swing.JButton addSp9;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbIDSP;
    private javax.swing.JLabel lbIIDDongSP;
    private javax.swing.JLabel lbIIdMauSac;
    private javax.swing.JLabel lbIIdNSX;
    private javax.swing.JTable tblDongSP;
    private javax.swing.JTable tblMauSac;
    private javax.swing.JTable tblNSX;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JLabel txtIdNhanVien;
    private javax.swing.JTextField txtMaDongSP;
    private javax.swing.JTextField txtMaMauSac;
    private javax.swing.JTextField txtMaNSX;
    private javax.swing.JLabel txtMaNV;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtTenDongSP;
    private javax.swing.JTextField txtTenMauSac;
    private javax.swing.JTextField txtTenNSX;
    private javax.swing.JLabel txtTenNV;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables
}
