/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import utilities.mycompany.DBConext.HibernatUtil;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import domainModels.ChiTietSanPham;
import domainModels.DongSP;
import domainModels.MauSac;
import domainModels.NSX;
import domainModels.SanPham;
import services.ChiTietSanPhamService;
import services.DongSpService;
import services.MauSacService;
import services.NSXService;
import services.SPService;
import viewModels.ChiTietSanPhamViewModel;
import viewModels.DongSPVmodel;
import viewModels.MauSacViewModel;
import viewModels.NSXViewModel;
import viewModels.SanPhamVModel;
import services.Impl.IManageChiTietSanPhamService;
import services.Impl.IManageDongSPService;
import services.Impl.IManageMauSacService;
import services.Impl.IManageNSXService;
import services.Impl.IManageSanPhamService;

/**
 *
 * @author Admin
 */
public class viewChiTietSanPham extends javax.swing.JFrame {

    /**
     * Creates new form viewChiTietSanPham
     */
    private final IManageChiTietSanPhamService serviceSP = new ChiTietSanPhamService();
    private final IManageSanPhamService SP = new SPService();
    private final IManageDongSPService dongspService = new DongSpService();
    private final IManageMauSacService MauService = new MauSacService();
    private final IManageNSXService NsxService = new NSXService();
    DefaultTableModel model = new DefaultTableModel();

    public viewChiTietSanPham(String Id, String Ma, String Ten) {
        initComponents();
        txtIdNhanVien.setText(Id);
        txtMaNV.setText(Ma);
        txtTenNV.setText(Ten);
        loadSP();
        loadNSXcbc();
        loadDongcbc();
        loadSPcbc();
        loadMaucbc();
    }

    public void loadSP() {
        model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);
        List<ChiTietSanPhamViewModel> list = serviceSP.list();
        for (ChiTietSanPhamViewModel a : list) {
            model.addRow(new Object[]{
                a.getId(), a.getTenSP(), a.getTenNSX(), a.getMauSac(),
                a.getDongSP(), a.getNamBH(), a.getMoTa(), a.getSoLuongTon(),
                a.getGiaBan(), a.getGiaNhap()
            });
        }

    }

    public void loadSPcbc() {
        List<SanPhamVModel> list = SP.getSp();
        for (SanPhamVModel sanPham : list) {
            cbcsp.addItem(sanPham.getTen());
        }
    }

    public void loadNSXcbc() {
        List<NSXViewModel> list = NsxService.getNSX();
        for (NSXViewModel s : list) {
            cbcNsx.addItem(s.getTen());
        }
    }

    public void loadMaucbc() {
        List<MauSacViewModel> list = MauService.getlist();
        for (MauSacViewModel s : list) {
            cbcmausac.addItem(s.getTen());
        }
    }

    public void loadDongcbc() {
        List<DongSPVmodel> list = dongspService.getlist();
        for (DongSPVmodel s : list) {
            cbcdong.addItem(s.getTen());
        }
    }
////////////////////////////////////////////////////////////

    public String getiDsP(String ten) {
        String id = "";
        List<SanPhamVModel> list = SP.getSp();
        for (SanPhamVModel s : list) {
            if (s.getTen().equals(ten)) {
                id = s.getId();
            }
        }
        return id;
    }

    public String getidnsx(String ten) {
        String id = "";
        List<NSXViewModel> list = NsxService.getNSX();
        for (NSXViewModel s : list) {
            if (s.getTen().equals(ten)) {
                id = s.getId();
            }
        }
        return id;
    }

    public String getidmausac(String ten) {
        String id = "";
        List<MauSacViewModel> list = MauService.getlist();
        for (MauSacViewModel s : list) {
            if (s.getTen().equals(ten)) {
                id = s.getId();
            }
        }
        return id;
    }

    public String getidDongSP(String ten) {
        String id = "";
        List<DongSPVmodel> list = dongspService.getlist();
        for (DongSPVmodel s : list) {
            if (s.getTen().equals(ten)) {
                id = s.getId();
            }
        }
        return id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        cbcsp = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbcNsx = new javax.swing.JComboBox<>();
        cbcmausac = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbcdong = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtGiaNhap = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        txtSoLuongTon = new javax.swing.JTextField();
        txtNamBaoHanh = new javax.swing.JTextField();
        txtId = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        txtIdNhanVien = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        tblSanPham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "TenSP", "Tên Nhà SX", "Màu Sắc", "Dòng SP", "Nam BH", "Mô Tả", "Số Lượng Tồn", "Giá Nhập", "Giá Bán"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        cbcsp.setBackground(new java.awt.Color(153, 153, 255));
        cbcsp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbcsp.setForeground(new java.awt.Color(255, 255, 255));
        cbcsp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        cbcsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcspActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tên Sản Phẩm");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tên Nhá Sản Xuất");

        cbcNsx.setBackground(new java.awt.Color(153, 153, 255));
        cbcNsx.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbcNsx.setForeground(new java.awt.Color(255, 255, 255));
        cbcNsx.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 51, 51)));

        cbcmausac.setBackground(new java.awt.Color(153, 153, 255));
        cbcmausac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbcmausac.setForeground(new java.awt.Color(255, 255, 255));
        cbcmausac.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 102, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Màu Sắc");

        cbcdong.setBackground(new java.awt.Color(153, 153, 255));
        cbcdong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbcdong.setForeground(new java.awt.Color(255, 255, 255));
        cbcdong.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dòng Sản Phẩm");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mô Tả");

        txtMoTa.setBackground(new java.awt.Color(153, 153, 255));
        txtMoTa.setColumns(20);
        txtMoTa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMoTa.setForeground(new java.awt.Color(255, 255, 255));
        txtMoTa.setRows(5);
        txtMoTa.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 3, 0, new java.awt.Color(102, 255, 204)));
        txtMoTa.setCaretColor(new java.awt.Color(102, 102, 255));
        jScrollPane2.setViewportView(txtMoTa);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Năm Bảo Hành");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Số Lượng Tồn");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Giá Nhập");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Giá Bán");

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/themmoiicon.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/updateicon.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/androidIcon.png"))); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.setForeground(new java.awt.Color(153, 153, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/coffeShop.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtGiaNhap.setBackground(new java.awt.Color(153, 153, 255));
        txtGiaNhap.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txtGiaNhap.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(153, 0, 153)));

        txtGiaBan.setBackground(new java.awt.Color(153, 153, 255));
        txtGiaBan.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txtGiaBan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(153, 0, 153)));

        txtSoLuongTon.setBackground(new java.awt.Color(153, 153, 255));
        txtSoLuongTon.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txtSoLuongTon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(153, 0, 153)));

        txtNamBaoHanh.setBackground(new java.awt.Color(153, 153, 255));
        txtNamBaoHanh.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txtNamBaoHanh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(153, 0, 153)));

        txtId.setText("Id");

        jPanel15.setBackground(new java.awt.Color(153, 153, 255));

        txtIdNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtIdNhanVien.setText("Id");

        txtMaNV.setBackground(new java.awt.Color(153, 153, 255));
        txtMaNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMaNV.setText("Ma NV");

        txtTenNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTenNV.setText("Ten NV");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(txtIdNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtIdNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(41, 41, 41))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(70, 70, 70))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(58, 58, 58)))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbcdong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbcmausac, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNamBaoHanh))
                                    .addComponent(cbcsp, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbcNsx, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9))
                                .addGap(85, 85, 85))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(77, 77, 77)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGiaBan)
                            .addComponent(txtSoLuongTon, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 110, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(80, 80, 80))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbcsp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbcNsx, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbcmausac, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(cbcdong, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(13, 13, 13))
                                .addComponent(txtGiaBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtNamBaoHanh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MenuView v = new MenuView(txtIdNhanVien.getText(), txtMaNV.getText(), txtTenNV.getText());
        v.setLocationRelativeTo(null);
        v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cbcspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcspActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        int index = tblSanPham.getSelectedRow();
        String idhd = tblSanPham.getValueAt(index, 0).toString();
        String tensp = tblSanPham.getValueAt(index, 1).toString();
        String nsx = tblSanPham.getValueAt(index, 2).toString();
        String mausac = tblSanPham.getValueAt(index, 3).toString();
        String dong = tblSanPham.getValueAt(index, 4).toString();
        String nambg = tblSanPham.getValueAt(index, 5).toString();
        String mota = tblSanPham.getValueAt(index, 6).toString();
        String soluong = tblSanPham.getValueAt(index, 7).toString();
        String nhap = tblSanPham.getValueAt(index, 8).toString();
        String ban = tblSanPham.getValueAt(index, 9).toString();
        txtId.setText(idhd);
        cbcsp.setSelectedItem(tensp);
        cbcNsx.setSelectedItem(nsx);
        cbcmausac.setSelectedItem(mausac);
        cbcdong.setSelectedItem(dong);

        txtNamBaoHanh.setText(nambg);
        txtMoTa.setText(mota);
        txtSoLuongTon.setText(soluong);
        txtGiaNhap.setText(nhap);
        txtGiaBan.setText(ban);
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ChiTietSanPham sp = new ChiTietSanPham();
        String idsp = getiDsP((String) cbcsp.getSelectedItem());
        String idnsx = getidnsx((String) cbcNsx.getSelectedItem());
        String idmausac = getidmausac((String) cbcmausac.getSelectedItem());
        String idDongSP = getidDongSP((String) cbcdong.getSelectedItem());
        int NamBH = Integer.parseInt(txtNamBaoHanh.getText());
        String MoTa = txtMoTa.getText();
        int SoLuong = Integer.parseInt(txtSoLuongTon.getText());
        BigDecimal GiaNhap = BigDecimal.valueOf(Integer.parseInt(txtGiaNhap.getText()));
        BigDecimal GiaBan = BigDecimal.valueOf(Integer.parseInt(txtGiaBan.getText()));

        //  CARCK
        // set
        sp.setNamBH(NamBH);
        sp.setMoTa(MoTa);
        sp.setSoLuongTon(SoLuong);
        sp.setGiaNhap(GiaNhap);
        sp.setGiaBan(GiaBan);
//
        boolean e = serviceSP.add(sp, idsp, idnsx, idmausac, idDongSP);
        if (e == true) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/themmoiicon.png"));
            JOptionPane.showMessageDialog(this, "Thêm Sản Phẩm Thành Công", "Giỏ Hàng", JOptionPane.INFORMATION_MESSAGE, icon);
            loadSP();
        } else {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/deleteicon.png"));
            JOptionPane.showMessageDialog(this, "Thêm Sản Phẩm Thất Bại", "Giỏ Hàng !", JOptionPane.INFORMATION_MESSAGE, icon);
        }
        System.out.println(sp.toString());


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ChiTietSanPham sp = new ChiTietSanPham();
        String idsp = getiDsP((String) cbcsp.getSelectedItem());
        String idnsx = getidnsx((String) cbcNsx.getSelectedItem());
        String idmausac = getidmausac((String) cbcmausac.getSelectedItem());
        String idDongSP = getidDongSP((String) cbcdong.getSelectedItem());
        int NamBH = Integer.parseInt(txtNamBaoHanh.getText());
        String MoTa = txtMoTa.getText();
        int SoLuong = Integer.parseInt(txtSoLuongTon.getText());
        BigDecimal GiaNhap = BigDecimal.valueOf(Integer.parseInt(txtGiaNhap.getText()));
        BigDecimal GiaBan = BigDecimal.valueOf(Integer.parseInt(txtGiaBan.getText()));

        //  CARCK
        // set
        sp.setNamBH(NamBH);
        sp.setMoTa(MoTa);
        sp.setSoLuongTon(SoLuong);
        sp.setGiaNhap(GiaNhap);
        sp.setGiaBan(GiaBan);
//
        boolean e = serviceSP.update(sp, idsp, idnsx, idmausac, idDongSP, txtId.getText());
        if (e == true) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/themmoiicon.png"));
            JOptionPane.showMessageDialog(this, "Update Sản Phẩm Thành Công", "Giỏ Hàng", JOptionPane.INFORMATION_MESSAGE, icon);
            loadSP();
        } else {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/deleteicon.png"));
            JOptionPane.showMessageDialog(this, "Update Sản Phẩm Thất Bại", "Giỏ Hàng !", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean b = serviceSP.Delete(txtId.getText());
        if (b == true) {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/themmoiicon.png"));
            JOptionPane.showMessageDialog(this, "Delete Sản Phẩm Thành Công", "Giỏ Hàng", JOptionPane.INFORMATION_MESSAGE, icon);
            loadSP();
        } else {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/img_icon/deleteicon.png"));
            JOptionPane.showMessageDialog(this, "Sản Phẩm Đã Được Giao Bán Vì Vậy Không Xóa Mà Update Số Lượng Về 0", "Giỏ Hàng !", JOptionPane.INFORMATION_MESSAGE, icon);
            boolean e = serviceSP.updateXoa(txtId.getText());
            if (e == true) {
                Icon icon1 = new javax.swing.ImageIcon(getClass().getResource("/img_icon/themmoiicon.png"));
                JOptionPane.showMessageDialog(this, "Đã Chuyển Số Lượng Về 0", "Giỏ Hàng", JOptionPane.INFORMATION_MESSAGE, icon1);
                loadSP();
            } else {
                Icon icon1 = new javax.swing.ImageIcon(getClass().getResource("/img_icon/deleteicon.png"));
                JOptionPane.showMessageDialog(this, "Update Sản Phẩm Thất Bại", "Giỏ Hàng !", JOptionPane.INFORMATION_MESSAGE, icon1);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewChiTietSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewChiTietSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewChiTietSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewChiTietSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbcNsx;
    private javax.swing.JComboBox<String> cbcdong;
    private javax.swing.JComboBox<String> cbcmausac;
    private javax.swing.JComboBox<String> cbcsp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtIdNhanVien;
    private javax.swing.JLabel txtMaNV;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtNamBaoHanh;
    private javax.swing.JTextField txtSoLuongTon;
    private javax.swing.JLabel txtTenNV;
    // End of variables declaration//GEN-END:variables
}
